googleapis/api-client-staging

- generated/nodejs/google-cloud-node/packages/errorreporting/src/index.js
- generated/nodejs/google-cloud-node/packages/errorreporting/src/v1beta1/index.js
This is a follow-up PR to https://github.com/googleapis/api-client-staging/pull/4
> Minor comment fix and add 'use strict'

- generated/ruby/google-cloud-ruby/google-cloud-error_reporting/README.md
- generated/ruby/google-cloud-ruby/google-cloud-error_reporting/google-cloud-error_reporting.gemspec
- generated/ruby/google-cloud-ruby/google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1.rb
* Remove version number in the gem name
* Use Stackdriver name
> Hand edit files in errorreporting

- generated/nodejs/google-cloud-node/packages/errorreporting/README.md
- generated/nodejs/google-cloud-node/packages/errorreporting/package.json
- generated/nodejs/google-cloud-node/packages/errorreporting/src/v1beta1/error_group_service_api.js
- generated/nodejs/google-cloud-node/packages/errorreporting/src/v1beta1/error_stats_service_api.js
- generated/nodejs/google-cloud-node/packages/errorreporting/src/v1beta1/report_errors_service_api.js
Use 'Stackdriver' for naming API in package.json and README.md
Update google-gax dependency to 0.7.0
Remove arguejs dependency
> Update errorreporting for nodejs

- generated/php/google-cloud-language-v1beta1/src/Language/V1Beta1/LanguageServiceApi.php
- generated/php/google-cloud-language-v1beta1/src/Language/V1Beta1/resources/language_service_client_config.json
- generated/php/google-cloud-speech-v1beta1/src/Speech/V1beta1/SpeechApi.php
- generated/php/google-cloud-speech-v1beta1/src/Speech/V1beta1/resources/speech_client_config.json
- generated/php/google-cloud-vision-v1/src/Vision/V1/ImageAnnotatorApi.php
- generated/php/google-cloud-vision-v1/src/Vision/V1/resources/image_annotator_client_config.json
- generated/php/google-devtools-clouderrorreporting-v1beta1/src/Errorreporting/V1beta1/ErrorGroupServiceApi.php
- generated/php/google-devtools-clouderrorreporting-v1beta1/src/Errorreporting/V1beta1/ErrorStatsServiceApi.php
- generated/php/google-devtools-clouderrorreporting-v1beta1/src/Errorreporting/V1beta1/ReportErrorsServiceApi.php
- generated/php/google-devtools-clouderrorreporting-v1beta1/src/Errorreporting/V1beta1/resources/error_group_service_client_config.json
- generated/php/google-devtools-clouderrorreporting-v1beta1/src/Errorreporting/V1beta1/resources/error_stats_service_client_config.json
- generated/php/google-devtools-clouderrorreporting-v1beta1/src/Errorreporting/V1beta1/resources/report_errors_service_client_config.json
- generated/php/google-devtools-cloudtrace-v1/src/Trace/V1/TraceServiceApi.php
- generated/php/google-devtools-cloudtrace-v1/src/Trace/V1/resources/trace_service_client_config.json
- generated/php/google-monitoring-v3/src/Monitoring/V3/GroupServiceApi.php
- generated/php/google-monitoring-v3/src/Monitoring/V3/MetricServiceApi.php
- generated/php/google-monitoring-v3/src/Monitoring/V3/resources/group_service_client_config.json
- generated/php/google-monitoring-v3/src/Monitoring/V3/resources/metric_service_client_config.json
- ErrorReporting
- Speech
- Vision
- Monitoring
- Trace
- Language
> Generate new APIs for PHP

- generated/python/test/trace.py
This makes the test correspond to the NodeJS test in
https://github.com/googleapis/api-client-staging/pull/77
> Add list method to Python Trace integration test

- generated/go/google-cloud-speech-v1beta1/cloud.google.com/go/speech/apiv1beta1/speech_client.go
- generated/go/google-cloud-speech-v1beta1/cloud.google.com/go/speech/apiv1beta1/speech_client_example_test.go
- generated/go/google-logging-v2/cloud.google.com/go/logging/apiv2/doc.go
- generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/publisher_client.go
- generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/publisher_client_example_test.go
- generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/subscriber_client.go
- generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/subscriber_client_example_test.go
- Use LRO library
- Fix some whitespace
> Regenerate Go clients

- generated/go/google-iam-admin-v1/cloud.google.com/go/iam/admin/apiv1/iam_client.go
- generated/go/google-iam-admin-v1/cloud.google.com/go/iam/admin/apiv1/iam_client_example_test.go
This commit reflects the configuration change introduced in
https://github.com/googleapis/googleapis/pull/178 .
> Go: Regenerate IAM Admin

- generated/java/build.gradle
- generated/java/google-cloud-error-reporting-v1beta1/src/test/java/com/google/cloud/errorreporting/spi/v1beta1/ReportErrorsServiceSmokeTest.java
- generated/java/google-cloud-language-v1beta1/src/test/java/com/google/cloud/language/spi/v1beta1/LanguageServiceSmokeTest.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/LoggingServiceV2SmokeTest.java
- generated/java/google-cloud-monitoring-v3/src/test/java/com/google/cloud/monitoring/spi/v3/MetricServiceSmokeTest.java
- generated/java/google-cloud-pubsub-v1/src/test/java/com/google/cloud/pubsub/spi/v1/PublisherSmokeTest.java
- generated/java/google-cloud-speech-v1beta1/src/test/java/com/google/cloud/speech/spi/v1beta1/SpeechSmokeTest.java
- generated/java/google-cloud-trace-v1/src/test/java/com/google/cloud/trace/spi/v1/TraceServiceSmokeTest.java
- generated/java/google-cloud-vision-v1/src/test/java/com/google/cloud/vision/spi/v1/ImageAnnotatorSmokeTest.java
> Add generated smoke tests for Java.

- generated/java/build.gradle
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/ConfigServiceV2Client.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/LoggingServiceV2Client.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/MetricsServiceV2Client.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/package-info.java
- generated/java/google-cloud-speech-v1beta1/src/main/java/com/google/cloud/speech/spi/v1beta1/SpeechClient.java
- generated/java/google-cloud-speech-v1beta1/src/main/java/com/google/cloud/speech/spi/v1beta1/SpeechSettings.java
- generated/java/google-cloud-speech-v1beta1/src/test/java/com/google/cloud/speech/spi/v1beta1/SpeechSmokeTest.java
- generated/java/google-cloud-speech-v1beta1/src/test/java/com/google/cloud/speech/spi/v1beta1/SpeechTest.java
- generated/java/google-cloud-vision-v1/src/test/java/com/google/cloud/vision/spi/v1/ImageAnnotatorSmokeTest.java
This should match the google-cloud-java PR.
> Java: updating logging docs and speech LRO

- generated/go/google-cloud-language-v1/cloud.google.com/go/language/apiv1/mock_test.go
- generated/go/google-cloud-speech-v1beta1/cloud.google.com/go/speech/apiv1beta1/mock_test.go
- generated/go/google-cloud-vision-v1/cloud.google.com/go/vision/apiv1/mock_test.go
- generated/go/google-devtools-clouddebugger-v2/cloud.google.com/go/debugger/apiv2/mock_test.go
- generated/go/google-devtools-clouderrorreporting-v1beta1/cloud.google.com/go/errorreporting/apiv1beta1/error_stats_client.go
- generated/go/google-devtools-clouderrorreporting-v1beta1/cloud.google.com/go/errorreporting/apiv1beta1/mock_test.go
- generated/go/google-devtools-cloudtrace-v1/cloud.google.com/go/trace/apiv1/mock_test.go
- generated/go/google-devtools-cloudtrace-v1/cloud.google.com/go/trace/apiv1/trace_client.go
- generated/go/google-iam-admin-v1/cloud.google.com/go/iam/admin/apiv1/iam_client.go
- generated/go/google-iam-admin-v1/cloud.google.com/go/iam/admin/apiv1/mock_test.go
- generated/go/google-logging-v2/cloud.google.com/go/logging/apiv2/config_client.go
- generated/go/google-logging-v2/cloud.google.com/go/logging/apiv2/logging_client.go
- generated/go/google-logging-v2/cloud.google.com/go/logging/apiv2/metrics_client.go
- generated/go/google-logging-v2/cloud.google.com/go/logging/apiv2/mock_test.go
- generated/go/google-monitoring-v3/cloud.google.com/go/monitoring/apiv3/group_client.go
- generated/go/google-monitoring-v3/cloud.google.com/go/monitoring/apiv3/metric_client.go
- generated/go/google-monitoring-v3/cloud.google.com/go/monitoring/apiv3/mock_test.go
- generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/mock_test.go
- generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/publisher_client.go
- generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/subscriber_client.go
Adds unit testing and a bug fix for iterators
> regenerate go from toolkit

- generated/python/gapic-google-cloud-logging-v2-docs/docs/conf.py
- generated/python/gapic-google-cloud-logging-v2-docs/tox.ini
Switch to use Sphinx classic theme.
> Switch to use Sphinx classic theme.

- generated/python/gapic-google-cloud-logging-v2-docs/docs/conf.py
Set numpydoc_show_class_members to False in conf.py
> Set numpydoc_show_class_members to False in conf.py

- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/ConfigServiceV2Client.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/LoggingServiceV2Client.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/MetricsServiceV2Client.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/package-info.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/ConfigServiceV2Test.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/LoggingServiceV2SmokeTest.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/LoggingServiceV2Test.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/MetricsServiceV2Test.java
See this PR for gapic yaml update: https://github.com/googleapis/googleapis/pull/208
> Update Java logging with resource names

- generated/java/build.gradle
Grpc packages are published to maven
> Bump grpc version to 0.1.4

- generated/php/google-cloud-error-reporting-v1beta1/src/Errorreporting/V1beta1/ErrorGroupServiceClient.php
- generated/php/google-cloud-error-reporting-v1beta1/src/Errorreporting/V1beta1/ErrorStatsServiceClient.php
- generated/php/google-cloud-error-reporting-v1beta1/src/Errorreporting/V1beta1/ReportErrorsServiceClient.php
- generated/php/google-cloud-language-v1/src/Language/V1/LanguageServiceClient.php
- generated/php/google-cloud-logging-v2/src/Logging/V2/ConfigServiceV2Client.php
- generated/php/google-cloud-logging-v2/src/Logging/V2/LoggingServiceV2Client.php
- generated/php/google-cloud-logging-v2/src/Logging/V2/MetricsServiceV2Client.php
- generated/php/google-cloud-monitoring-v3/src/Monitoring/V3/GroupServiceClient.php
- generated/php/google-cloud-monitoring-v3/src/Monitoring/V3/MetricServiceClient.php
- generated/php/google-cloud-pubsub-v1/src/PubSub/V1/PublisherClient.php
- generated/php/google-cloud-pubsub-v1/src/PubSub/V1/SubscriberClient.php
- generated/php/google-cloud-speech-v1beta1/src/Speech/V1beta1/SpeechClient.php
- generated/php/google-cloud-trace-v1/src/Trace/V1/TraceServiceClient.php
- generated/php/google-cloud-vision-v1/src/Vision/V1/ImageAnnotatorClient.php
- Get GAX version from GAX instead of hard coded
- Add note about experimental status
- Proto comment updates
> Regenerate PHP

- docs/requirements.txt
- generated/python/gapic-google-cloud-logging-v2-docs/docs/conf.py
- generated/python/gapic-google-cloud-logging-v2-docs/tox.ini
Add docs/requirements.txt to specified package location for RTD doc generation. Switch back to RTD theme.
> Add docs/requirements.txt for RTD doc generation

- generated/python/gapic-google-cloud-datastore-v1/MANIFEST.in
- generated/python/gapic-google-cloud-datastore-v1/setup.py
- generated/python/gapic-google-cloud-logging-v2/MANIFEST.in
- generated/python/gapic-google-cloud-logging-v2/setup.py
- generated/python/gapic-google-cloud-pubsub-v1/MANIFEST.in
- generated/python/gapic-google-cloud-pubsub-v1/setup.py
- generated/python/gapic-google-cloud-speech-v1beta1/MANIFEST.in
- generated/python/gapic-google-cloud-speech-v1beta1/setup.py
- generated/python/gapic-google-cloud-vision-v1/MANIFEST.in
- generated/python/gapic-google-cloud-vision-v1/setup.py
Updates GoogleCloudPlatform/google-cloud-python#2913, googleapis/toolkit#892
> Exclude pyc files from all current GAPIC packages

- generated/java/build.gradle
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/PublisherClient.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/SubscriberClient.java
- generated/java/google-cloud-pubsub-v1/src/test/java/com/google/cloud/pubsub/spi/v1/SubscriberClientTest.java
- generated/java/google-cloud-speech-v1beta1/src/main/java/com/google/cloud/speech/spi/v1beta1/SpeechClient.java
- generated/java/google-cloud-speech-v1beta1/src/test/java/com/google/cloud/speech/spi/v1beta1/SpeechClientTest.java
This depends on gax 0.0.30 being released.
> Regenerating Java: StreamObserver -> RpcStreamObserver

- generated/python/proto-google-cloud-pubsub-v1/google/cloud/proto/pubsub/v1/pubsub_pb2.py
- generated/python/proto-google-cloud-pubsub-v1/google/cloud/proto/pubsub/v1/pubsub_pb2_grpc.py
- generated/python/proto-google-cloud-pubsub-v1/setup.py
This fixes a trailing comma, gets some updates from the protos, and bumps the version to 0.15.1.
> Python: New Pubsub Proto Package

- generated/nodejs/google-cloud-node/packages/pubsub/package.json
- generated/nodejs/google-cloud-node/packages/pubsub/src/v1/publisher_client.js
- generated/nodejs/google-cloud-node/packages/pubsub/src/v1/publisher_client_config.json
- generated/nodejs/google-cloud-node/packages/pubsub/src/v1/subscriber_client.js
- generated/nodejs/google-cloud-node/packages/pubsub/src/v1/subscriber_client_config.json
- generated/nodejs/google-cloud-node/packages/pubsub/test/test.js
Covers HTTP headers and grpc options
> Update pubsub API client for NodeJS

- generated/python/gapic-google-cloud-logging-v2/docs/conf.py
- generated/python/gapic-google-cloud-logging-v2/google/cloud/gapic/logging/v2/config_service_v2_client.py
- generated/python/gapic-google-cloud-logging-v2/google/cloud/gapic/logging/v2/config_service_v2_client_config.json
- generated/python/gapic-google-cloud-logging-v2/google/cloud/gapic/logging/v2/logging_service_v2_client.py
- generated/python/gapic-google-cloud-logging-v2/google/cloud/gapic/logging/v2/logging_service_v2_client_config.json
- generated/python/gapic-google-cloud-logging-v2/google/cloud/gapic/logging/v2/metrics_service_v2_client.py
- generated/python/gapic-google-cloud-logging-v2/google/cloud/gapic/logging/v2/metrics_service_v2_client_config.json
- generated/python/gapic-google-cloud-logging-v2/requirements.txt
- generated/python/gapic-google-cloud-logging-v2/setup.py
- generated/python/proto-google-cloud-logging-v2/setup.py
@geigerj This one is also hand-edited.
> Python Logging GAPIC 0.91.3

- generated/python/gapic-google-cloud-spanner-admin-database-v1/docs/conf.py
- generated/python/gapic-google-cloud-spanner-admin-database-v1/docs/index.rst
- generated/python/gapic-google-cloud-spanner-admin-database-v1/google/cloud/gapic/spanner_admin_database/v1/database_admin_client.py
- generated/python/gapic-google-cloud-spanner-admin-database-v1/google/cloud/gapic/spanner_admin_database/v1/database_admin_client_config.json
- generated/python/gapic-google-cloud-spanner-admin-database-v1/requirements.txt
- generated/python/gapic-google-cloud-spanner-admin-database-v1/setup.py
- generated/python/gapic-google-cloud-spanner-admin-instance-v1/docs/conf.py
- generated/python/gapic-google-cloud-spanner-admin-instance-v1/docs/index.rst
- generated/python/gapic-google-cloud-spanner-admin-instance-v1/google/cloud/gapic/spanner_admin_instance/v1/instance_admin_client.py
- generated/python/gapic-google-cloud-spanner-admin-instance-v1/google/cloud/gapic/spanner_admin_instance/v1/instance_admin_client_config.json
- generated/python/gapic-google-cloud-spanner-admin-instance-v1/requirements.txt
- generated/python/gapic-google-cloud-spanner-admin-instance-v1/setup.py
- generated/python/gapic-google-cloud-spanner-v1/README.rst
- generated/python/gapic-google-cloud-spanner-v1/docs/conf.py
- generated/python/gapic-google-cloud-spanner-v1/docs/index.rst
- generated/python/gapic-google-cloud-spanner-v1/docs/starting.rst
- generated/python/gapic-google-cloud-spanner-v1/google/cloud/gapic/spanner/v1/spanner_client.py
- generated/python/gapic-google-cloud-spanner-v1/google/cloud/gapic/spanner/v1/spanner_client_config.json
- generated/python/gapic-google-cloud-spanner-v1/requirements.txt
- generated/python/gapic-google-cloud-spanner-v1/setup.py
- generated/python/proto-google-cloud-spanner-admin-database-v1/setup.py
- generated/python/proto-google-cloud-spanner-admin-instance-v1/setup.py
- generated/python/proto-google-cloud-spanner-v1/setup.py
This includes `spanner`, `spanner_admin_database`, and `spanner_admin_instance`.
> Python Spanner GAPIC 0.15.3

- generated/python/gapic-google-cloud-datastore-v1/docs/conf.py
- generated/python/gapic-google-cloud-datastore-v1/google/cloud/gapic/datastore/v1/datastore_client.py
- generated/python/gapic-google-cloud-datastore-v1/google/cloud/gapic/datastore/v1/datastore_client_config.json
- generated/python/gapic-google-cloud-datastore-v1/requirements.txt
- generated/python/gapic-google-cloud-datastore-v1/setup.py
- generated/python/proto-google-cloud-datastore-v1/setup.py
This will likely be the highest risk of the new autogen GAPICs because it has hand-edits.
> Python Datastore GAPIC.

- generated/java/build.gradle
- generated/java/google-cloud-error-reporting-v1beta1/src/test/java/com/google/cloud/errorreporting/spi/v1beta1/ErrorGroupServiceClientTest.java
- generated/java/google-cloud-error-reporting-v1beta1/src/test/java/com/google/cloud/errorreporting/spi/v1beta1/ErrorStatsServiceClientTest.java
- generated/java/google-cloud-error-reporting-v1beta1/src/test/java/com/google/cloud/errorreporting/spi/v1beta1/ReportErrorsServiceClientTest.java
- generated/java/google-cloud-language-v1/src/test/java/com/google/cloud/language/spi/v1/LanguageServiceClientTest.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/ConfigClientTest.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/LoggingClientTest.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/MetricsClientTest.java
- generated/java/google-cloud-monitoring-v3/src/test/java/com/google/cloud/monitoring/spi/v3/GroupServiceClientTest.java
- generated/java/google-cloud-monitoring-v3/src/test/java/com/google/cloud/monitoring/spi/v3/MetricServiceClientTest.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/PagedResponseWrappers.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/SubscriptionAdminClient.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/SubscriptionAdminSettings.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/TopicAdminClient.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/TopicAdminSettings.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/package-info.java
- generated/java/google-cloud-pubsub-v1/src/test/java/com/google/cloud/pubsub/spi/v1/MockSubscriberImpl.java
- generated/java/google-cloud-pubsub-v1/src/test/java/com/google/cloud/pubsub/spi/v1/SubscriptionAdminClientTest.java
- generated/java/google-cloud-pubsub-v1/src/test/java/com/google/cloud/pubsub/spi/v1/TopicAdminClientTest.java
- generated/java/google-cloud-pubsub-v1/src/test/java/com/google/cloud/pubsub/spi/v1/TopicAdminSmokeTest.java
- generated/java/google-cloud-speech-v1beta1/src/test/java/com/google/cloud/speech/spi/v1beta1/SpeechClientTest.java
- generated/java/google-cloud-trace-v1/src/test/java/com/google/cloud/trace/spi/v1/TraceServiceClientTest.java
- generated/java/google-cloud-vision-v1/src/test/java/com/google/cloud/vision/spi/v1/ImageAnnotatorClientTest.java
This picks up the Pubsub changes, and the changing of exception test error code. See https://github.com/googleapis/api-client-staging/pull/211 for discussion
> Regenerate all Java APIs

- generated/java/build.gradle
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/ConfigClient.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/LoggingClient.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/LoggingSettings.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/MetricsClient.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/TopicAdminSettings.java
Partially supersedes https://github.com/googleapis/api-client-staging/pull/214 (I'm not regenerating Speech)
> Java regeneration: PartitionKey, @ExperimentalApi

- generated/java/build.gradle
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/LoggingSettings.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/TopicAdminSettings.java
- generated/java/google-cloud-speech-v1beta1/src/main/java/com/google/cloud/speech/spi/v1beta1/SpeechClient.java
reflects googleapis/toolkit#1153 .
> java: update generated code

- generated/java/build.gradle
- generated/java/google-cloud-error-reporting-v1beta1/src/main/java/com/google/cloud/errorreporting/spi/v1beta1/ErrorGroupServiceSettings.java
- generated/java/google-cloud-error-reporting-v1beta1/src/main/java/com/google/cloud/errorreporting/spi/v1beta1/ErrorStatsServiceSettings.java
- generated/java/google-cloud-error-reporting-v1beta1/src/main/java/com/google/cloud/errorreporting/spi/v1beta1/ReportErrorsServiceSettings.java
- generated/java/google-cloud-language-v1/src/main/java/com/google/cloud/language/spi/v1/LanguageServiceSettings.java
- generated/java/google-cloud-language-v1beta2/src/main/java/com/google/cloud/language/spi/v1beta2/LanguageServiceSettings.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/ConfigSettings.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/LoggingSettings.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/MetricsSettings.java
- generated/java/google-cloud-monitoring-v3/src/main/java/com/google/cloud/monitoring/spi/v3/GroupServiceSettings.java
- generated/java/google-cloud-monitoring-v3/src/main/java/com/google/cloud/monitoring/spi/v3/MetricServiceSettings.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/SubscriptionAdminSettings.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/TopicAdminSettings.java
- generated/java/google-cloud-speech-v1/src/main/java/com/google/cloud/speech/spi/v1/SpeechSettings.java
- generated/java/google-cloud-speech-v1beta1/src/main/java/com/google/cloud/speech/spi/v1beta1/SpeechSettings.java
- generated/java/google-cloud-trace-v1/src/main/java/com/google/cloud/trace/spi/v1/TraceServiceSettings.java
- generated/java/google-cloud-vision-v1/src/main/java/com/google/cloud/vision/spi/v1/ImageAnnotatorSettings.java
- Also updated the polling interval for Speech v1
> Refresh Java gapic clients with updated property path

- generated/java/build.gradle
- settings.gradle
- Add speech v1 and language v1beta2 projects and dependencies.
- Reorder to alphabetical
> Reorder and add required projects

- generated/java/build.gradle
- generated/java/google-cloud-error-reporting-v1beta1/src/test/java/com/google/cloud/errorreporting/spi/v1beta1/MockErrorGroupService.java
- generated/java/google-cloud-error-reporting-v1beta1/src/test/java/com/google/cloud/errorreporting/spi/v1beta1/MockErrorStatsService.java
- generated/java/google-cloud-error-reporting-v1beta1/src/test/java/com/google/cloud/errorreporting/spi/v1beta1/MockReportErrorsService.java
- generated/java/google-cloud-language-v1/src/test/java/com/google/cloud/language/spi/v1/MockLanguageService.java
- generated/java/google-cloud-language-v1beta2/src/test/java/com/google/cloud/language/spi/v1beta2/MockLanguageService.java
- generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/LoggingSettings.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/LoggingClientTest.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/MockConfigServiceV2.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/MockLoggingServiceV2.java
- generated/java/google-cloud-logging-v2/src/test/java/com/google/cloud/logging/spi/v2/MockMetricsServiceV2.java
- generated/java/google-cloud-monitoring-v3/src/test/java/com/google/cloud/monitoring/spi/v3/MockGroupService.java
- generated/java/google-cloud-monitoring-v3/src/test/java/com/google/cloud/monitoring/spi/v3/MockMetricService.java
- generated/java/google-cloud-pubsub-v1/src/main/java/com/google/cloud/pubsub/spi/v1/TopicAdminSettings.java
- generated/java/google-cloud-pubsub-v1/src/test/java/com/google/cloud/pubsub/spi/v1/MockIAMPolicy.java
- generated/java/google-cloud-pubsub-v1/src/test/java/com/google/cloud/pubsub/spi/v1/MockPublisher.java
- generated/java/google-cloud-pubsub-v1/src/test/java/com/google/cloud/pubsub/spi/v1/MockSubscriber.java
- generated/java/google-cloud-spanner-admin-database-v1/src/test/java/com/google/cloud/spanner/admin/database/spi/v1/MockDatabaseAdmin.java
- generated/java/google-cloud-spanner-admin-instance-v1/src/test/java/com/google/cloud/spanner/admin/instance/spi/v1/MockInstanceAdmin.java
- generated/java/google-cloud-spanner-v1/src/test/java/com/google/cloud/spanner/spi/v1/MockSpanner.java
- generated/java/google-cloud-speech-v1/src/test/java/com/google/cloud/speech/spi/v1/MockSpeech.java
- generated/java/google-cloud-trace-v1/src/test/java/com/google/cloud/trace/spi/v1/MockTraceService.java
- generated/java/google-cloud-vision-v1/src/test/java/com/google/cloud/vision/spi/v1/MockImageAnnotator.java
- generated/java/google-longrunning-v1/src/test/java/com/google/longrunning/MockOperations.java
Generated using googleapis/toolkit#1197 .
> Java: removing usage of deprecated methods

- .circleci/config.yml
- generated/python/.gitignore
- generated/python/nox.py
This commit adds a CI setup for Python. WIP.
_In its current state, the actual tests should fail_, because the existing code on master right now has failing tests.
> Python CI.

- generated/python/nox.py
This will fix the datastore install.
> Do not use -e on pip install here.

- composer.json
- Fix version of PHPUnit
- Bump GAX to version with fix: https://github.com/googleapis/gax-php/pull/85
> Update composer to support PHP 7

- generated/nodejs/.gitignore
- generated/nodejs/package.json
- generated/nodejs/videointelligence/README.md
- generated/nodejs/videointelligence/package.json
- generated/nodejs/videointelligence/src/index.js
- generated/nodejs/videointelligence/src/v1beta1/index.js
- generated/nodejs/videointelligence/src/v1beta1/video_intelligence_service_client.js
- generated/nodejs/videointelligence/src/v1beta1/video_intelligence_service_client_config.json
- generated/nodejs/videointelligence/test/gapic-v1beta1.js
> Nodejs GAPIC: Video-intelligence v1beta1

- generated/nodejs/dlp/README.md
- generated/nodejs/dlp/package.json
- generated/nodejs/dlp/smoke-test/dlp_service_smoke_test.js
- generated/nodejs/dlp/src/index.js
- generated/nodejs/dlp/src/v2beta1/dlp_service_client.js
- generated/nodejs/dlp/src/v2beta1/dlp_service_client_config.json
- generated/nodejs/dlp/src/v2beta1/index.js
- generated/nodejs/dlp/test/gapic-v2beta1.js
> Nodejs GAPIC: Dlp v2beta1

- generated/java/build.gradle
- generated/java/gapic-google-cloud-dlp-v2beta1/src/test/java/com/google/cloud/dlp/v2beta1/DlpServiceClientTest.java
- generated/java/gapic-google-cloud-error-reporting-v1beta1/src/test/java/com/google/cloud/errorreporting/v1beta1/ErrorGroupServiceClientTest.java
- generated/java/gapic-google-cloud-error-reporting-v1beta1/src/test/java/com/google/cloud/errorreporting/v1beta1/ErrorStatsServiceClientTest.java
- generated/java/gapic-google-cloud-error-reporting-v1beta1/src/test/java/com/google/cloud/errorreporting/v1beta1/ReportErrorsServiceClientTest.java
- generated/java/gapic-google-cloud-language-v1/src/test/java/com/google/cloud/language/v1/LanguageServiceClientTest.java
- generated/java/gapic-google-cloud-language-v1beta2/src/test/java/com/google/cloud/language/v1beta2/LanguageServiceClientTest.java
- generated/java/gapic-google-cloud-logging-v2/src/test/java/com/google/cloud/logging/v2/ConfigClientTest.java
- generated/java/gapic-google-cloud-logging-v2/src/test/java/com/google/cloud/logging/v2/LoggingClientTest.java
- generated/java/gapic-google-cloud-logging-v2/src/test/java/com/google/cloud/logging/v2/MetricsClientTest.java
- generated/java/gapic-google-cloud-monitoring-v3/src/test/java/com/google/cloud/monitoring/v3/GroupServiceClientTest.java
- generated/java/gapic-google-cloud-monitoring-v3/src/test/java/com/google/cloud/monitoring/v3/MetricServiceClientTest.java
- generated/java/gapic-google-cloud-pubsub-v1/src/test/java/com/google/cloud/pubsub/v1/SubscriptionAdminClientTest.java
- generated/java/gapic-google-cloud-pubsub-v1/src/test/java/com/google/cloud/pubsub/v1/TopicAdminClientTest.java
- generated/java/gapic-google-cloud-spanner-admin-database-v1/src/test/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClientTest.java
- generated/java/gapic-google-cloud-spanner-admin-instance-v1/src/test/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClientTest.java
- generated/java/gapic-google-cloud-spanner-v1/src/test/java/com/google/cloud/spanner/v1/SpannerClientTest.java
- generated/java/gapic-google-cloud-speech-v1/src/test/java/com/google/cloud/speech/v1/SpeechClientTest.java
- generated/java/gapic-google-cloud-speech-v1beta1/src/test/java/com/google/cloud/speech/v1beta1/SpeechClientTest.java
- generated/java/gapic-google-cloud-trace-v1/src/test/java/com/google/cloud/trace/v1/TraceServiceClientTest.java
- generated/java/gapic-google-cloud-video-intelligence-v1beta1/src/test/java/com/google/cloud/videointelligence/v1beta1/VideoIntelligenceServiceClientTest.java
- generated/java/gapic-google-cloud-vision-v1/src/test/java/com/google/cloud/vision/v1/ImageAnnotatorClientTest.java
- generated/java/gapic-google-longrunning-v1/src/test/java/com/google/longrunning/OperationsClientTest.java
Tests are updated with latest toolkit & GAX change.
> Refresh Java

- generated/java/gapic-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/LanguageServiceClient.java
- generated/java/gapic-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/LanguageServiceSettings.java
- generated/java/gapic-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/stub/GrpcLanguageServiceStub.java
- generated/java/gapic-google-cloud-language-v1/src/main/java/com/google/cloud/language/v1/stub/LanguageServiceStub.java
- generated/java/gapic-google-cloud-language-v1/src/test/java/com/google/cloud/language/v1/LanguageServiceClientTest.java
- generated/java/gapic-google-cloud-language-v1/src/test/java/com/google/cloud/language/v1/MockLanguageServiceImpl.java
> Java: refresh NL v1 library

- generated/php/google-cloud-dlp-v2beta1/src/Dlp/V2beta1/Gapic/DlpServiceGapicClient.php
- generated/php/google-cloud-dlp-v2beta1/src/Dlp/V2beta1/resources/dlp_service_client_config.json
- generated/php/google-cloud-dlp-v2beta1/tests/unit/Dlp/V2beta1/DlpServiceClientTest.php
- generated/php/google-cloud-error-reporting-v1beta1/src/ErrorReporting/V1beta1/Gapic/ErrorGroupServiceGapicClient.php
- generated/php/google-cloud-error-reporting-v1beta1/src/ErrorReporting/V1beta1/Gapic/ErrorStatsServiceGapicClient.php
- generated/php/google-cloud-error-reporting-v1beta1/src/ErrorReporting/V1beta1/Gapic/ReportErrorsServiceGapicClient.php
- generated/php/google-cloud-firestore-v1beta1/src/Firestore/V1beta1/Gapic/FirestoreGapicClient.php
- generated/php/google-cloud-language-v1/src/Language/V1/Gapic/LanguageServiceGapicClient.php
- generated/php/google-cloud-language-v1beta2/src/Language/V1beta2/Gapic/LanguageServiceGapicClient.php
- generated/php/google-cloud-logging-v2/src/Logging/V2/Gapic/ConfigServiceV2GapicClient.php
- generated/php/google-cloud-logging-v2/src/Logging/V2/Gapic/LoggingServiceV2GapicClient.php
- generated/php/google-cloud-logging-v2/src/Logging/V2/Gapic/MetricsServiceV2GapicClient.php
- generated/php/google-cloud-monitoring-v3/src/Monitoring/V3/Gapic/GroupServiceGapicClient.php
- generated/php/google-cloud-monitoring-v3/src/Monitoring/V3/Gapic/MetricServiceGapicClient.php
- generated/php/google-cloud-pubsub-v1/src/PubSub/V1/Gapic/PublisherGapicClient.php
- generated/php/google-cloud-pubsub-v1/src/PubSub/V1/Gapic/SubscriberGapicClient.php
- generated/php/google-cloud-spanner-admin-database-v1/src/Spanner/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
- generated/php/google-cloud-spanner-admin-instance-v1/src/Spanner/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
- generated/php/google-cloud-spanner-v1/src/Spanner/V1/Gapic/SpannerGapicClient.php
- generated/php/google-cloud-speech-v1/src/Speech/V1/Gapic/SpeechGapicClient.php
- generated/php/google-cloud-speech-v1beta1/src/Speech/V1beta1/Gapic/SpeechGapicClient.php
- generated/php/google-cloud-video-intelligence-v1beta1/src/VideoIntelligence/V1beta1/Gapic/VideoIntelligenceServiceGapicClient.php
- generated/php/google-cloud-video-intelligence-v1beta2/src/VideoIntelligence/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php
- generated/php/google-cloud-vision-v1/src/Vision/V1/Gapic/ImageAnnotatorGapicClient.php
- generated/php/google-longrunning-v1/src/GAX/LongRunning/Gapic/OperationsGapicClient.php
1) Fix php-cs-fixer phpdoc_annotation_without_dot issue
2) Put back dlp gapic client class example
> Fix PHP generated files

- generated/php/google-cloud-bigtable-admin-v2/src/Bigtable/Admin/V2/Gapic/BigtableInstanceAdminGapicClient.php
- generated/php/google-cloud-dlp-v2beta1/src/Dlp/V2beta1/Gapic/DlpServiceGapicClient.php
- generated/php/google-cloud-pubsub-v1/src/PubSub/V1/Gapic/SubscriberGapicClient.php
- generated/php/google-cloud-pubsub-v1/tests/unit/PubSub/V1/SubscriberClientTest.php
- generated/php/google-cloud-spanner-admin-database-v1/src/Spanner/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
- generated/php/google-cloud-spanner-admin-instance-v1/src/Spanner/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
- generated/php/google-cloud-speech-v1/src/Speech/V1/Gapic/SpeechGapicClient.php
- generated/php/google-cloud-speech-v1beta1/src/Speech/V1beta1/Gapic/SpeechGapicClient.php
- generated/php/google-cloud-video-intelligence-v1/src/VideoIntelligence/V1/Gapic/VideoIntelligenceServiceGapicClient.php
- generated/php/google-cloud-video-intelligence-v1beta1/src/VideoIntelligence/V1beta1/Gapic/VideoIntelligenceServiceGapicClient.php
- generated/php/google-cloud-video-intelligence-v1beta2/src/VideoIntelligence/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php
Pick up https://github.com/googleapis/toolkit/pull/1709 and latest googleapis changes
> Refresh PHP gapics

- generated/php/google-cloud-container-v1/tests/system/Container/V1/ClusterManagerSmokeTest.php
> Php GAPIC: Container v1

- generated/php/google-cloud-bigquerydatatransfer-v1/tests/system/BigQuery/DataTransfer/V1/DataTransferServiceSmokeTest.php
> Php GAPIC: Bigquerydatatransfer v1

- generated/php/google-cloud-trace-v1/tests/system/Trace/V1/TraceServiceSmokeTest.php
Manually edit smoke test for trace, pending approval/release of googleapis/toolkit#1740
> Fix trace system test

- generated/php/google-cloud-debugger-v2/src/Debugger/V2/Controller2Client.php
- generated/php/google-cloud-debugger-v2/src/Debugger/V2/Debugger2Client.php
- generated/php/google-cloud-debugger-v2/src/Debugger/V2/Gapic/Controller2GapicClient.php
- generated/php/google-cloud-debugger-v2/src/Debugger/V2/Gapic/Debugger2GapicClient.php
- generated/php/google-cloud-debugger-v2/tests/unit/Debugger/V2/Controller2ClientTest.php
- generated/php/google-cloud-debugger-v2/tests/unit/Debugger/V2/Debugger2ClientTest.php
- generated/php/google-cloud-debugger-v2/tests/unit/Debugger/V2/MockController2Impl.php
- generated/php/google-cloud-debugger-v2/tests/unit/Debugger/V2/MockDebugger2Impl.php
> Php GAPIC: Debugger v2

- generated/php/google-cloud-dlp-v2beta1/composer.json
- generated/php/google-cloud-dlp-v2beta1/proto/src/Google/Cloud/Dlp/V2beta1/RecordCondition_Expressions_LogicalOperator.php
- generated/php/google-cloud-dlp-v2beta1/src/Dlp/V2beta1/DlpServiceClient.php
- generated/php/google-cloud-dlp-v2beta1/src/Dlp/V2beta1/Gapic/DlpServiceGapicClient.php
- generated/php/google-cloud-dlp-v2beta1/tests/system/Dlp/V2beta1/DlpServiceSmokeTest.php
- generated/php/google-cloud-dlp-v2beta1/tests/unit/Dlp/V2beta1/DlpServiceClientTest.php
- generated/php/google-cloud-dlp-v2beta1/tests/unit/Dlp/V2beta1/MockDlpServiceImpl.php
- generated/php/google-cloud-dlp-v2beta1/tests/unit/Dlp/V2beta1/MockOperationsImpl.php
> Php GAPIC: Dlp v2beta1

- generated/php/google-cloud-error-reporting-v1beta1/composer.json
- generated/php/google-cloud-error-reporting-v1beta1/src/ErrorReporting/V1beta1/ErrorGroupServiceClient.php
- generated/php/google-cloud-error-reporting-v1beta1/src/ErrorReporting/V1beta1/ErrorStatsServiceClient.php
- generated/php/google-cloud-error-reporting-v1beta1/src/ErrorReporting/V1beta1/Gapic/ErrorGroupServiceGapicClient.php
- generated/php/google-cloud-error-reporting-v1beta1/src/ErrorReporting/V1beta1/Gapic/ErrorStatsServiceGapicClient.php
- generated/php/google-cloud-error-reporting-v1beta1/src/ErrorReporting/V1beta1/Gapic/ReportErrorsServiceGapicClient.php
- generated/php/google-cloud-error-reporting-v1beta1/src/ErrorReporting/V1beta1/ReportErrorsServiceClient.php
- generated/php/google-cloud-error-reporting-v1beta1/tests/system/ErrorReporting/V1beta1/ReportErrorsServiceSmokeTest.php
- generated/php/google-cloud-error-reporting-v1beta1/tests/unit/ErrorReporting/V1beta1/ErrorGroupServiceClientTest.php
- generated/php/google-cloud-error-reporting-v1beta1/tests/unit/ErrorReporting/V1beta1/ErrorStatsServiceClientTest.php
- generated/php/google-cloud-error-reporting-v1beta1/tests/unit/ErrorReporting/V1beta1/MockErrorGroupServiceImpl.php
- generated/php/google-cloud-error-reporting-v1beta1/tests/unit/ErrorReporting/V1beta1/MockErrorStatsServiceImpl.php
- generated/php/google-cloud-error-reporting-v1beta1/tests/unit/ErrorReporting/V1beta1/MockReportErrorsServiceImpl.php
- generated/php/google-cloud-error-reporting-v1beta1/tests/unit/ErrorReporting/V1beta1/ReportErrorsServiceClientTest.php
> Php GAPIC: Error-reporting v1beta1

- generated/php/google-cloud-language-v1/composer.json
- generated/php/google-cloud-language-v1/proto/src/Google/Cloud/Language/V1/DependencyEdge_Label.php
- generated/php/google-cloud-language-v1/src/Language/V1/Gapic/LanguageServiceGapicClient.php
- generated/php/google-cloud-language-v1/src/Language/V1/LanguageServiceClient.php
- generated/php/google-cloud-language-v1/tests/system/Language/V1/LanguageServiceSmokeTest.php
- generated/php/google-cloud-language-v1/tests/unit/Language/V1/LanguageServiceClientTest.php
- generated/php/google-cloud-language-v1/tests/unit/Language/V1/MockLanguageServiceImpl.php
> Php GAPIC: Language v1

- generated/php/google-cloud-language-v1beta2/composer.json
- generated/php/google-cloud-language-v1beta2/proto/src/Google/Cloud/Language/V1beta2/DependencyEdge_Label.php
- generated/php/google-cloud-language-v1beta2/src/Language/V1beta2/Gapic/LanguageServiceGapicClient.php
- generated/php/google-cloud-language-v1beta2/src/Language/V1beta2/LanguageServiceClient.php
- generated/php/google-cloud-language-v1beta2/tests/system/Language/V1beta2/LanguageServiceSmokeTest.php
- generated/php/google-cloud-language-v1beta2/tests/unit/Language/V1beta2/LanguageServiceClientTest.php
- generated/php/google-cloud-language-v1beta2/tests/unit/Language/V1beta2/MockLanguageServiceImpl.php
> Php GAPIC: Language v1beta2

- generated/php/google-cloud-logging-v2/composer.json
- generated/php/google-cloud-logging-v2/src/Logging/V2/ConfigServiceV2Client.php
- generated/php/google-cloud-logging-v2/src/Logging/V2/Gapic/ConfigServiceV2GapicClient.php
- generated/php/google-cloud-logging-v2/src/Logging/V2/Gapic/LoggingServiceV2GapicClient.php
- generated/php/google-cloud-logging-v2/src/Logging/V2/Gapic/MetricsServiceV2GapicClient.php
- generated/php/google-cloud-logging-v2/src/Logging/V2/LoggingServiceV2Client.php
- generated/php/google-cloud-logging-v2/src/Logging/V2/MetricsServiceV2Client.php
- generated/php/google-cloud-logging-v2/tests/system/Logging/V2/LoggingServiceV2SmokeTest.php
- generated/php/google-cloud-logging-v2/tests/unit/Logging/V2/ConfigServiceV2ClientTest.php
- generated/php/google-cloud-logging-v2/tests/unit/Logging/V2/LoggingServiceV2ClientTest.php
- generated/php/google-cloud-logging-v2/tests/unit/Logging/V2/MetricsServiceV2ClientTest.php
- generated/php/google-cloud-logging-v2/tests/unit/Logging/V2/MockConfigServiceV2Impl.php
- generated/php/google-cloud-logging-v2/tests/unit/Logging/V2/MockLoggingServiceV2Impl.php
- generated/php/google-cloud-logging-v2/tests/unit/Logging/V2/MockMetricsServiceV2Impl.php
> Php GAPIC: Logging v2

- generated/php/google-cloud-firestore-v1beta1/composer.json
- generated/php/google-cloud-firestore-v1beta1/proto/src/Google/Cloud/Firestore/V1beta1/StructuredQuery_CompositeFilter_Operator.php
- generated/php/google-cloud-firestore-v1beta1/src/Firestore/V1beta1/FirestoreClient.php
- generated/php/google-cloud-firestore-v1beta1/src/Firestore/V1beta1/Gapic/FirestoreGapicClient.php
- generated/php/google-cloud-firestore-v1beta1/tests/unit/Firestore/V1beta1/FirestoreClientTest.php
- generated/php/google-cloud-firestore-v1beta1/tests/unit/Firestore/V1beta1/MockFirestoreImpl.php
> Php GAPIC: Firestore v1beta1

- generated/php/google-cloud-pubsub-v1/composer.json
- generated/php/google-cloud-pubsub-v1/src/PubSub/V1/Gapic/PublisherGapicClient.php
- generated/php/google-cloud-pubsub-v1/src/PubSub/V1/Gapic/SubscriberGapicClient.php
- generated/php/google-cloud-pubsub-v1/src/PubSub/V1/PublisherClient.php
- generated/php/google-cloud-pubsub-v1/src/PubSub/V1/SubscriberClient.php
- generated/php/google-cloud-pubsub-v1/tests/system/PubSub/V1/PublisherSmokeTest.php
- generated/php/google-cloud-pubsub-v1/tests/unit/PubSub/V1/MockIAMPolicyImpl.php
- generated/php/google-cloud-pubsub-v1/tests/unit/PubSub/V1/MockPublisherImpl.php
- generated/php/google-cloud-pubsub-v1/tests/unit/PubSub/V1/MockSubscriberImpl.php
- generated/php/google-cloud-pubsub-v1/tests/unit/PubSub/V1/PublisherClientTest.php
- generated/php/google-cloud-pubsub-v1/tests/unit/PubSub/V1/SubscriberClientTest.php
> Php GAPIC: Pubsub v1

- generated/php/google-cloud-spanner-v1/composer.json
- generated/php/google-cloud-spanner-v1/src/Spanner/V1/Gapic/SpannerGapicClient.php
- generated/php/google-cloud-spanner-v1/src/Spanner/V1/SpannerClient.php
- generated/php/google-cloud-spanner-v1/tests/unit/Spanner/V1/MockSpannerImpl.php
- generated/php/google-cloud-spanner-v1/tests/unit/Spanner/V1/SpannerClientTest.php
> Php GAPIC: Spanner v1

- generated/php/google-cloud-spanner-admin-database-v1/composer.json
- generated/php/google-cloud-spanner-admin-database-v1/src/Spanner/Admin/Database/V1/DatabaseAdminClient.php
- generated/php/google-cloud-spanner-admin-database-v1/src/Spanner/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
- generated/php/google-cloud-spanner-admin-database-v1/tests/unit/Spanner/Admin/Database/V1/DatabaseAdminClientTest.php
- generated/php/google-cloud-spanner-admin-database-v1/tests/unit/Spanner/Admin/Database/V1/MockDatabaseAdminImpl.php
- generated/php/google-cloud-spanner-admin-database-v1/tests/unit/Spanner/Admin/Database/V1/MockOperationsImpl.php
> Php GAPIC: Spanner-admin-database v1

- generated/php/google-cloud-spanner-admin-instance-v1/composer.json
- generated/php/google-cloud-spanner-admin-instance-v1/src/Spanner/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
- generated/php/google-cloud-spanner-admin-instance-v1/src/Spanner/Admin/Instance/V1/InstanceAdminClient.php
- generated/php/google-cloud-spanner-admin-instance-v1/tests/unit/Spanner/Admin/Instance/V1/InstanceAdminClientTest.php
- generated/php/google-cloud-spanner-admin-instance-v1/tests/unit/Spanner/Admin/Instance/V1/MockInstanceAdminImpl.php
- generated/php/google-cloud-spanner-admin-instance-v1/tests/unit/Spanner/Admin/Instance/V1/MockOperationsImpl.php
> Php GAPIC: Spanner-admin-instance v1

- generated/php/google-cloud-speech-v1/composer.json
- generated/php/google-cloud-speech-v1/src/Speech/V1/Gapic/SpeechGapicClient.php
- generated/php/google-cloud-speech-v1/src/Speech/V1/SpeechClient.php
- generated/php/google-cloud-speech-v1/tests/system/Speech/V1/SpeechSmokeTest.php
- generated/php/google-cloud-speech-v1/tests/unit/Speech/V1/MockOperationsImpl.php
- generated/php/google-cloud-speech-v1/tests/unit/Speech/V1/MockSpeechImpl.php
- generated/php/google-cloud-speech-v1/tests/unit/Speech/V1/SpeechClientTest.php
> Php GAPIC: Speech v1

- generated/php/google-cloud-speech-v1beta1/composer.json
- generated/php/google-cloud-speech-v1beta1/src/Speech/V1beta1/Gapic/SpeechGapicClient.php
- generated/php/google-cloud-speech-v1beta1/src/Speech/V1beta1/SpeechClient.php
- generated/php/google-cloud-speech-v1beta1/tests/system/Speech/V1beta1/SpeechSmokeTest.php
- generated/php/google-cloud-speech-v1beta1/tests/unit/Speech/V1beta1/MockOperationsImpl.php
- generated/php/google-cloud-speech-v1beta1/tests/unit/Speech/V1beta1/MockSpeechImpl.php
- generated/php/google-cloud-speech-v1beta1/tests/unit/Speech/V1beta1/SpeechClientTest.php
> Php GAPIC: Speech v1beta1

- generated/php/google-cloud-trace-v2/composer.json
- generated/php/google-cloud-trace-v2/src/Trace/V2/Gapic/TraceServiceGapicClient.php
- generated/php/google-cloud-trace-v2/src/Trace/V2/TraceServiceClient.php
- generated/php/google-cloud-trace-v2/tests/system/Trace/V2/TraceServiceSmokeTest.php
- generated/php/google-cloud-trace-v2/tests/unit/Trace/V2/MockTraceServiceImpl.php
- generated/php/google-cloud-trace-v2/tests/unit/Trace/V2/TraceServiceClientTest.php
> Php GAPIC: Trace v2

- generated/php/google-cloud-video-intelligence-v1/composer.json
- generated/php/google-cloud-video-intelligence-v1/src/VideoIntelligence/V1/Gapic/VideoIntelligenceServiceGapicClient.php
- generated/php/google-cloud-video-intelligence-v1/src/VideoIntelligence/V1/VideoIntelligenceServiceClient.php
- generated/php/google-cloud-video-intelligence-v1/tests/system/VideoIntelligence/V1/VideoIntelligenceServiceSmokeTest.php
- generated/php/google-cloud-video-intelligence-v1/tests/unit/VideoIntelligence/V1/MockOperationsImpl.php
- generated/php/google-cloud-video-intelligence-v1/tests/unit/VideoIntelligence/V1/MockVideoIntelligenceServiceImpl.php
- generated/php/google-cloud-video-intelligence-v1/tests/unit/VideoIntelligence/V1/VideoIntelligenceServiceClientTest.php
> Php GAPIC: Video-intelligence v1

- generated/php/google-cloud-video-intelligence-v1beta1/composer.json
- generated/php/google-cloud-video-intelligence-v1beta1/src/VideoIntelligence/V1beta1/Gapic/VideoIntelligenceServiceGapicClient.php
- generated/php/google-cloud-video-intelligence-v1beta1/src/VideoIntelligence/V1beta1/VideoIntelligenceServiceClient.php
- generated/php/google-cloud-video-intelligence-v1beta1/tests/unit/VideoIntelligence/V1beta1/MockOperationsImpl.php
- generated/php/google-cloud-video-intelligence-v1beta1/tests/unit/VideoIntelligence/V1beta1/MockVideoIntelligenceServiceImpl.php
- generated/php/google-cloud-video-intelligence-v1beta1/tests/unit/VideoIntelligence/V1beta1/VideoIntelligenceServiceClientTest.php
> Php GAPIC: Video-intelligence v1beta1

- generated/php/google-cloud-video-intelligence-v1beta2/composer.json
- generated/php/google-cloud-video-intelligence-v1beta2/src/VideoIntelligence/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php
- generated/php/google-cloud-video-intelligence-v1beta2/src/VideoIntelligence/V1beta2/VideoIntelligenceServiceClient.php
- generated/php/google-cloud-video-intelligence-v1beta2/tests/unit/VideoIntelligence/V1beta2/MockOperationsImpl.php
- generated/php/google-cloud-video-intelligence-v1beta2/tests/unit/VideoIntelligence/V1beta2/MockVideoIntelligenceServiceImpl.php
- generated/php/google-cloud-video-intelligence-v1beta2/tests/unit/VideoIntelligence/V1beta2/VideoIntelligenceServiceClientTest.php
> Php GAPIC: Video-intelligence v1beta2

- generated/php/google-cloud-vision-v1/composer.json
- generated/php/google-cloud-vision-v1/src/Vision/V1/Gapic/ImageAnnotatorGapicClient.php
- generated/php/google-cloud-vision-v1/src/Vision/V1/ImageAnnotatorClient.php
- generated/php/google-cloud-vision-v1/tests/system/Vision/V1/ImageAnnotatorSmokeTest.php
- generated/php/google-cloud-vision-v1/tests/unit/Vision/V1/ImageAnnotatorClientTest.php
- generated/php/google-cloud-vision-v1/tests/unit/Vision/V1/MockImageAnnotatorImpl.php
> Php GAPIC: Vision v1

- generated/php/google-cloud-dlp-v2/proto/src/Google/Cloud/Dlp/V2/Action_PublishToPubSub.php
- generated/php/google-cloud-dlp-v2/proto/src/Google/Cloud/Dlp/V2/DlpServiceGrpcClient.php
- generated/php/google-cloud-dlp-v2/proto/src/Google/Cloud/Dlp/V2/InspectDataSourceDetails_RequestedOptions.php
- generated/php/google-cloud-dlp-v2/src/Dlp/V2/Gapic/DlpServiceGapicClient.php
- generated/php/google-cloud-dlp-v2/src/Dlp/V2/resources/dlp_service_rest_client_config.php
> Php GAPIC: Dlp v2

- generated/java/grpc-google-appengine-v1/build.gradle
- generated/java/proto-google-appengine-v1/build.gradle
add missing version bumps in previous batch refresh
> Java: add missing version bump

- generated/python/googleapis-common-protos/setup.py
> Bump protobuf dep to 3.6.0 in googleapis-common-protos

- generated/python/grpc-google-iam-v1/setup.py
Includes the code generated from the new IAM protos: #671
> Releasing IAM v0.12.0

- generated/python/grpc-google-iam-v1/google/iam/v1/iam_policy_pb2.py
- generated/python/grpc-google-iam-v1/setup.py
Fixing a syntax error, and bumping a version.
> Fix dictionary syntax for __doc__, and bump version to 0.12.1

- generated/python/grpc-google-iam-v1/google/iam/v1/logging/audit_data_pb2.py
- generated/python/grpc-google-iam-v1/google/iam/v1/options_pb2.py
- generated/python/grpc-google-iam-v1/google/iam/v1/policy_pb2.py
- generated/python/grpc-google-iam-v1/setup.py
This `__doc__` thing is everywhere! Fixing that and releasing v0.12.2.
> fix more syntax errors and release 0.12.2

- generated/python/grpc-google-iam-v1/google/iam/v1/logging/audit_data_pb2.py
- generated/python/grpc-google-iam-v1/setup.py
Today it's the release day!  One more syntax error fix, and releasing v0.12.3.
> fix syntax for logging and release v0.12.3
