googleapis/api-client-staging

generated/python/gapic-google-cloud-language-v1beta1/setup.py, generated/python/gapic-google-cloud-vision-v1/setup.py, generated/python/gapic-google-logging-v2/setup.py, generated/python/gapic-google-pubsub-v1/setup.py, generated/python/grpc-google-cloud-language-v1beta1/setup.py, generated/python/grpc-google-cloud-vision-v1/setup.py, generated/python/grpc-google-iam-v1/setup.py, generated/python/grpc-google-logging-v2/setup.py, generated/python/grpc-google-pubsub-v1/setup.py
Mostly useful for logging, but being comprehensive.
See https://github.com/googleapis/api-client-staging/pull/50/files#diff-c534e11078a491e0fb0d0995ec8a76fcR1 for this new version of commonprotos.
=> Bump lower bound on commonprotos to 1.3.5.

generated/go/google-cloud-language-v1beta1/cloud.google.com/go/language/apiv1beta1/language_client.go, generated/go/google-cloud-speech-v1beta1/cloud.google.com/go/speech/apiv1beta1/speech_client.go, generated/go/google-cloud-speech-v1beta1/cloud.google.com/go/speech/apiv1beta1/speech_client_example_test.go, generated/go/google-cloud-vision-v1/cloud.google.com/go/vision/apiv1/doc.go, generated/go/google-cloud-vision-v1/cloud.google.com/go/vision/apiv1/image_annotator_client.go, generated/go/google-devtools-clouddebugger-v2/cloud.google.com/go/debugger/apiv2/controller2_client.go, generated/go/google-devtools-clouddebugger-v2/cloud.google.com/go/debugger/apiv2/debugger2_client.go, generated/go/google-devtools-clouddebugger-v2/cloud.google.com/go/debugger/apiv2/doc.go, generated/go/google-devtools-clouderrorreporting-v1beta1/cloud.google.com/go/errorreporting/apiv1beta1/error_group_client.go, generated/go/google-devtools-clouderrorreporting-v1beta1/cloud.google.com/go/errorreporting/apiv1beta1/error_stats_client.go, generated/go/google-devtools-clouderrorreporting-v1beta1/cloud.google.com/go/errorreporting/apiv1beta1/report_errors_client.go, generated/go/google-devtools-cloudtrace-v1/cloud.google.com/go/trace/apiv1/doc.go, generated/go/google-devtools-cloudtrace-v1/cloud.google.com/go/trace/apiv1/trace_client.go, generated/go/google-iam-admin-v1/cloud.google.com/go/iam/admin/apiv1/iam_client.go, generated/go/google-iam-admin-v1/cloud.google.com/go/iam/admin/apiv1/iam_client_example_test.go, generated/go/google-logging-v2/cloud.google.com/go/logging/apiv2/config_client.go, generated/go/google-logging-v2/cloud.google.com/go/logging/apiv2/doc.go, generated/go/google-logging-v2/cloud.google.com/go/logging/apiv2/logging_client.go, generated/go/google-logging-v2/cloud.google.com/go/logging/apiv2/metrics_client.go, generated/go/google-monitoring-v3/cloud.google.com/go/monitoring/apiv3/group_client.go, generated/go/google-monitoring-v3/cloud.google.com/go/monitoring/apiv3/metric_client.go, generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/doc.go, generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/publisher_client.go, generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/subscriber_client.go
This commit addsa few features
- GRPC streaming
- Metadata fix
- Point to domain layer, if one exists
- Disable iam/admin's Get, Set, and Test methods to be replaced with
hand-written version
=> Regenerate Go clients

generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/publisher_client.go, generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/publisher_client_example_test.go, generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/subscriber_client.go, generated/go/google-pubsub-v1/cloud.google.com/go/pubsub/apiv1/subscriber_client_example_test.go
This commit makes PubSub Topic and Subscription use the IAM library
at cloud.google.com/go/iam.
This is the state of the world after the following land:
- https://github.com/googleapis/googleapis/pull/175
- https://github.com/googleapis/toolkit/pull/627
=> Go pubsub/apiv1: Update IAM to use IAM library

generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/ConfigServiceV2Client.java, generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/LoggingServiceV2Client.java, generated/java/google-cloud-logging-v2/src/main/java/com/google/cloud/logging/spi/v2/MetricsServiceV2Client.java
Making use of https://github.com/googleapis/toolkit/pull/838 and https://github.com/googleapis/googleapis/pull/212 .
=> Java: regenerating Logging - removing @ExperimentalApi

generated/python/gapic-google-cloud-logging-v2/docs/conf.py, generated/python/gapic-google-cloud-logging-v2/google/cloud/gapic/logging/v2/config_service_v2_client.py, generated/python/gapic-google-cloud-logging-v2/google/cloud/gapic/logging/v2/logging_service_v2_client.py, generated/python/gapic-google-cloud-logging-v2/google/cloud/gapic/logging/v2/metrics_service_v2_client.py, generated/python/gapic-google-cloud-logging-v2/requirements.txt, generated/python/gapic-google-cloud-logging-v2/setup.py, generated/python/grpc-google-cloud-logging-v2/README.rst, generated/python/grpc-google-cloud-logging-v2/google/cloud/grpc/logging/v2/log_entry_pb2.py, generated/python/grpc-google-cloud-logging-v2/google/cloud/grpc/logging/v2/log_entry_pb2_grpc.py, generated/python/grpc-google-cloud-logging-v2/google/cloud/grpc/logging/v2/logging_config_pb2.py, generated/python/grpc-google-cloud-logging-v2/google/cloud/grpc/logging/v2/logging_config_pb2_grpc.py, generated/python/grpc-google-cloud-logging-v2/google/cloud/grpc/logging/v2/logging_metrics_pb2.py, generated/python/grpc-google-cloud-logging-v2/google/cloud/grpc/logging/v2/logging_metrics_pb2_grpc.py, generated/python/grpc-google-cloud-logging-v2/google/cloud/grpc/logging/v2/logging_pb2.py, generated/python/grpc-google-cloud-logging-v2/google/cloud/grpc/logging/v2/logging_pb2_grpc.py, generated/python/grpc-google-cloud-logging-v2/setup.py
@geigerj @dhermes This has the GAPIC config changes from @michaelbausor (https://github.com/googleapis/googleapis/pull/208). It is also built with the latest `grpcio 1.0.2rc0`, which wraps the gRPC code in `try-except`.
I believe this is ready for Beta. PTAL
=> Generate beta version of logging with latest grpcio and GAPIC config

generated/python/gapic-google-cloud-speech-v1beta1/docs/conf.py, generated/python/gapic-google-cloud-speech-v1beta1/docs/index.rst, generated/python/gapic-google-cloud-speech-v1beta1/google/cloud/gapic/speech/v1beta1/speech_client.py, generated/python/gapic-google-cloud-speech-v1beta1/google/cloud/gapic/speech/v1beta1/speech_client_config.json, generated/python/gapic-google-cloud-speech-v1beta1/requirements.txt, generated/python/gapic-google-cloud-speech-v1beta1/setup.py, generated/python/proto-google-cloud-speech-v1beta1/setup.py
This updates the Speech GAPIC based on proto changes and fixes a trailing comma in the proto package.
=> Speech regen / bump to 0.15.1

generated/python/gapic-google-cloud-datastore-v1/README.rst, generated/python/gapic-google-cloud-datastore-v1/docs/conf.py, generated/python/gapic-google-cloud-datastore-v1/docs/index.rst, generated/python/gapic-google-cloud-datastore-v1/google/cloud/gapic/datastore/v1/datastore_client.py, generated/python/gapic-google-cloud-datastore-v1/google/cloud/gapic/datastore/v1/datastore_client_config.json, generated/python/gapic-google-cloud-datastore-v1/requirements.txt, generated/python/gapic-google-cloud-datastore-v1/setup.py
A prerequisite step for https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3025
=> Datastore 0.15.1

generated/python/gapic-google-cloud-pubsub-v1/docs/conf.py, generated/python/gapic-google-cloud-pubsub-v1/docs/index.rst, generated/python/gapic-google-cloud-pubsub-v1/google/cloud/gapic/pubsub/v1/publisher_client.py, generated/python/gapic-google-cloud-pubsub-v1/google/cloud/gapic/pubsub/v1/publisher_client_config.json, generated/python/gapic-google-cloud-pubsub-v1/google/cloud/gapic/pubsub/v1/subscriber_client.py, generated/python/gapic-google-cloud-pubsub-v1/google/cloud/gapic/pubsub/v1/subscriber_client_config.json, generated/python/gapic-google-cloud-pubsub-v1/requirements.txt, generated/python/gapic-google-cloud-pubsub-v1/setup.py
This is the regenerated GAPIC for PubSub with the new methods defined in the proto.
This does **not** fix the issue in googleapis/toolkit#1061, which will require another regen. I assert that this is fine.
=> Regenerated GAPIC for Pubsub (0.15.1).

generated/nodejs/google-cloud-node/packages/spanner-admin-database/package.json, generated/nodejs/google-cloud-node/packages/spanner-admin-database/src/index.js, generated/nodejs/google-cloud-node/packages/spanner-admin-database/src/v1/database_admin_client.js, generated/nodejs/google-cloud-node/packages/spanner-admin-database/src/v1/database_admin_client_config.json, generated/nodejs/google-cloud-node/packages/spanner-admin-database/src/v1/index.js, generated/nodejs/google-cloud-node/packages/spanner-admin-database/test/test.js, generated/nodejs/google-cloud-node/packages/spanner-admin-instance/package.json, generated/nodejs/google-cloud-node/packages/spanner-admin-instance/src/index.js, generated/nodejs/google-cloud-node/packages/spanner-admin-instance/src/v1/index.js, generated/nodejs/google-cloud-node/packages/spanner-admin-instance/src/v1/instance_admin_client.js, generated/nodejs/google-cloud-node/packages/spanner-admin-instance/src/v1/instance_admin_client_config.json, generated/nodejs/google-cloud-node/packages/spanner-admin-instance/test/test.js, generated/nodejs/google-cloud-node/packages/spanner/package.json, generated/nodejs/google-cloud-node/packages/spanner/src/index.js, generated/nodejs/google-cloud-node/packages/spanner/src/v1/index.js, generated/nodejs/google-cloud-node/packages/spanner/src/v1/spanner_client.js, generated/nodejs/google-cloud-node/packages/spanner/src/v1/spanner_client_config.json, generated/nodejs/google-cloud-node/packages/spanner/test/test.js
This has several manual updates actually. We should fix those
manual efforts eventually;
- streaming methods with errors test cases fail. This is because
of nodejs behavior where delivery of 'data' events are queued
but unhandled 'error' events actually throw the error immediately.
See: https://github.com/googleapis/toolkit/issues/1108
- the path name and module name confusion for spanner admin
APIs.
=> Regenerate spanner clients.

.circleci/config.yml
This is a bogus baseline CI config so that I can properly set up the _actual_ configuration in a forthcoming pull request.
=> Add no-op CI config.

generated/python/nox.py
This fixes a problem that #233 exposed, which is that nox was configured to install the local `gapic-*` packages, but not the local `proto-*` packages, which are likely not to be on PyPI yet.
=> Install proto-* packages locally.

.circleci/config.yml, gradle/wrapper/gradle-wrapper.properties
Java unit tests pass in openjdk7 & 8 (Please ignore the python tests failures)
Note: This PR updates gradle to 2.11 since 2.0 gave us "peer not authenticated" error when resolving dependency.
=> Add Java CI

.circleci/config.yml, generated/nodejs/iam/package.json, generated/nodejs/runtests.sh
This PR makes unit tests run (and pass) in Node 4, bringing our Node coverage to all supported versions (as of this writing: 4, 6, and 7).
=> Fix Node 4 unit tests.

.circleci/config.yml, Dockerfile
The latest openJDK7 (131) image introduces a SSL security issue. (Already reported [here](https://github.com/docker-library/openjdk/issues/117))
An older version solves the test failures. We can revert to use the latest image once the issue is resolved at their end.
=> Set openjdk7 to use a specific version

generated/java/build.gradle, generated/java/google-longrunning-v1/build.gradle
gax dependency is updated to 1.4.1, following googleapis/gax-java#332.
google-longrunning-v1 now has its own build.gradle,
since its dependencies were removed
and inadvertently not replaced
in #361.
=> java: update gax dependency, making tests pass

.circleci/config.yml
Add PHP5 first. The unit tests are now having compatibility issues with PHP 7.*.
Note: A testing Docker image is built and pushed to Dockerhub:  @https://hub.docker.com/r/googleapis/php
TODO: Fix issues on PHP 7.
cc @landrito
=> Add CI for PHP 5

.circleci/config.yml
NOTE: Right now there is [an issue](https://github.com/googleapis/api-client-staging/issues/373) of running PHP tests on PHP 7.* I will add PHP 7 CI once the issue is fixed.
New PHP 5.5 docker pushed: https://hub.docker.com/r/googleapis/php/
=> Add CI for PHP 5.5

generated/php/google-cloud-pubsub-v1/tests/system/PubSub/V1/PublisherSmokeTest.php, phpunit-system.xml.dist
- Allow smoke tests to be present by excluding them from normal test runs
- Add smoke test for pubsub
- Add system test config that can be used to run smoke tests
Smoke tests for other APIs can be added when those APIs are refreshed. This PR does not cause smoke tests to be run as part of api-client-staging CI, as I expect that this would cause too many failures at this point.
=> Allow smoke tests to be present in PHP

.circleci/config.yml
CircleCI docker containers have problems unpacking GRPC pre-built binary for Node.js if run as root. That's reported as a separate issue. For now, let's run Node.js tests as non-root user which will save literally tens of minutes for each CI run.
=> Run node CI as non-root user

.circleci/config.yml
Java tests have been failing with exit code 137; after some research, it looks like the problem is memory usage. This change limits memory usage of gradle when running tests. I have verified by ssh into Circle that the tests pass now on both openjdk7 & openjdk8.
=> Fixing Java builds

generated/java/grpc-google-cloud-dlp-v2/build.gradle, generated/java/proto-google-cloud-dlp-v2/build.gradle
Grpc/proto package version for dlpv2 didn't get updated along with all the other APIs in the past commit.
=> Bump versions for dlpv2 too
